---
- name: Intall Nginx
  apt:
    name: nginx
    force_apt_get: yes
  
- name: Copy Nginx configuration
  copy:
    src: ../files/default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Start Nginx
  service:
    name: nginx
    state: started