---
- name: Intall Nginx
  apt:
    name: nginx
    state: present
    force_apt_get: yes
  
# lab02
# - name: Serve index.html
#   copy:
#     src: ../files
#     dest: /var/www/html
# lab02

# lab03
- name: Copy Nginx configuration
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Start Nginx
  service:
    name: nginx
    state: started
# lab03