{
 "title": "Lab07",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu{mode!=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable" }
   ]
  },
  { "title": "Bind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bind status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL queries per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Nginx requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  }
 ]
}