- name: Set up Bind and Bind exporter
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter
  tags: bind

- name: Update resolv conf
  hosts: all
  become: yes
  roles:
    - resolv
  tags: resolv

- name: Set up Prometheus Node exporters
  hosts: all
  become: yes
  roles:
    - node_exporters
  tags: node

- name: Set up Nginx and Nginx exporters
  hosts: web_servers
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags: nginx

- name: Set up Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
  tags: prometheus

- name: Reverse proxy
  hosts: all
  become: yes
  roles:
    - reverse_proxy
  tags: reverse_proxy

- name: Set up influxdb 
  hosts: influxdb
  become: yes
  roles:
    - influxdb
  tags: influxdb

- name: Set up rsyslog 
  hosts: all
  become: yes
  roles:
    - rsyslog
  tags: rsyslog

- name: Set up pinger
  hosts: pinger
  become: yes
  roles:
    - pinger
  tags: pinger


- name: Setup Docker
  hosts: docker
  become: yes
  roles:
    - docker
  tags: docker

- name: Setup Grafana Docker
  hosts: grafana
  become: yes
  roles:
    - grafana_docker
  tags: grafana

- name: Setup MySQL and MySQL exporter
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter
  tags: mysql

- name: Setup Agama Docker container
  hosts: app_servers
  become: yes
  roles:
    - agama_docker
  tags: agama

- name: Setup HAProxy, keepalived and its exporters
  hosts: haproxy
  become: yes
  roles:
    - keepalived
    - haproxy
  tags: haproxy