- name: Set up Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus # works after nginx
  tags: prometheus
  
- name: Set up Nginx and Nginx exporters
  hosts: web_servers
  become: yes
  roles:
    - nginx
    - nginx_exporter # works after prometheus
  tags: nginx

- name: Reverse proxy
  hosts: all
  become: yes
  roles:
    - reverse_proxy # works after nginx
  tags: reverse_proxy

- name: Set up Node exporters
  hosts: all
  become: yes
  roles:
    - node_exporters
  tags: node

- name: Set up Bind and Bind exporter
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter # works after prometheus
  tags: bind

- name: Update resolv conf
  hosts: all
  become: yes
  roles:
    - resolv # works after bind
  tags: resolv

- name: Set up influxdb 
  hosts: influxdb
  become: yes
  roles:
    - influxdb
  tags: influxdb

- name: Set up rsyslog 
  hosts: all
  become: yes
  roles:
    - rsyslog  # works after influxdb
  tags: rsyslog

- name: Set up pinger
  hosts: pinger
  become: yes
  roles:
    - pinger # works after influxdb
  tags: pinger

- name: Setup Docker
  hosts: docker
  become: yes
  roles:
    - docker
  tags: docker

- name: Setup Grafana Docker
  hosts: grafana
  become: yes
  roles:
    - grafana_docker # works after docker
  tags: grafana

- name: Setup MySQL and MySQL exporter
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter
  tags: mysql

- name: Setup Agama Docker container
  hosts: app_servers
  become: yes
  roles:
    - agama_docker # works after mysql
  tags: agama

- name: Setup HAProxy, keepalived and its exporters
  hosts: haproxy
  become: yes
  roles:
    - keepalived # works after agama
    - haproxy # works after agama
  tags: haproxy

- name: Setup backup
  hosts: all
  become: yes
  roles:
    - backup
  tags: backup