---
- name: Collect information about all VMs
  hosts: all
  tasks:
    - setup:

- name: DNS servers
  hosts: dns_server
  become: yes
  roles:
    - dns

- name: Change resolv.conf
  hosts: all
  become: yes
  roles:
    - resolv