---
- name: Install Node Exporters
  hosts: all
  become: yes
  roles:
    - node_exporters

- name: Install and configure Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus

- name: Configure reverse proxy
  hosts: all
  become: yes
  roles:
    - reverse_proxy