---
# - name: Install Docker
#   hosts: all
#   become: yes
#   roles: 
#     - docker

# - name: Set up Grafana Docker
#   hosts: grafana
#   become: yes
#   roles:
#     - grafana_docker
#     - reverse_proxy

- name: Set up MySQL server and MySQL exporter for Prometheus
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter

- name: Set up Agama Docker
  hosts: app_servers
  become: yes
  roles:
    - agama_docker
    - reverse_proxy
