---
- name: Intall Node Exporters
  apt:
    name: 
      - prometheus-node-exporter
    update_cache: yes
    force_apt_get: yes

- name: Make sure Node exporter is started
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
