---
- name: Create user backup and generate ssh key pairs
  user:
    name: backup
    create_home: yes
    shell: /bin/bash
    state: present
    generate_ssh_key: yes

- name: Create group 472
  group:
    name: "472"
    gid: 472
    state: present
  when: inventory_hostname in groups['grafana']

- name: Add user to 472
  user:
    name: backup
    groups: "472"
  when: inventory_hostname in groups['grafana']

- name: Add user to mysql
  user:
    name: backup
    groups: mysql
  when: inventory_hostname in groups['db_servers']

- name: Add user to prometheus
  user:
    name: backup
    groups: prometheus
  when: inventory_hostname in groups['prometheus']

- name: Create directories
  file:
    path: /home/backup/{{ item }}
    state: directory
    owner: backup
    group: backup
  loop:
    - backup
    - restore

- name: Create directories
  file:
    path: /home/backup/backup/grafana
    state: directory
    owner: backup
    group: backup
  when: inventory_hostname in groups['grafana']


- name: Create directories
  file:
    path: /home/backup/backup/prometheus
    state: directory
    owner: backup
    group: backup
  when: inventory_hostname in groups['prometheus']

- name: Create directories
  file:
    path: /home/backup/backup/mysql
    state: directory
    owner: backup
    group: backup
  when: inventory_hostname in groups['db_servers']

- name: Add conf for mysqldump
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: 'backup'
    mode: '0400'
  when: inventory_hostname in groups['db_servers']

- name: Create influxdb backup directory
  file:
    path: /home/backup/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: '0755'
  when: inventory_hostname == "vm2"

- name: Intall Duplicity
  apt:
    name: duplicity
    state: present
    force_apt_get: yes

- name: Schedule backup scripts
  copy:
    src: backup_{{ inventory_hostname }}
    dest: /etc/cron.d/backup

# SSH by backup
# ssh shyamajp@backup.premiumfriday.ttu

# dump by backup
# mysqldump agama > /home/backup/backup/agama.sql

# scp by backup
# scp agama.sql shyamajp@backup.premiumfriday.ttu:agama.sql

# copy to /home/backup/restore by backup
# rsync -v shyamajp@backup.premiumfriday.ttu:agama.sql restore/agama.sql

# restore by backup
# mysql agama < restore/agama.sql -u agama -p




# Duplicity
# dumplicity -no-encryption full agama.sql rsync://shyamajp@backup.premiumfriday.ttu//home/shyamajp
# dumplicity -no-encryption incremental agama.sql rsync://shyamajp@backup.premiumfriday.ttu//home/shyamajp
# dumplicity -no-encryption restore rsync://shyamajp@backup.premiumfriday.ttu//home/shyamajp/  restore/