---
- name: Create user backup and generate ssh key pairs
  user:
    name: backup
    state: present
    create_home: yes # default
    home: /home/backup # default
    generate_ssh_key: yes
    ssh_key_file: /home/backup/.ssh/id_rsa