---
- name: Install application dependencies
  apt:
    name: fping
    state: present
    force_apt_get: yes

- name: Create system user pinger
  user:
    name: pinger
    state: present
    system: yes

- name: Create directory /etc/pinger
  file:
    path: /etc/pinger
    state: directory

- name: Copy pinger.conf
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
    mode: '0644'
  notify: Restart influxdb

- name: Copy pinger.sh
  copy:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    mode: '0755' # must be executable(5), not (4)
  notify: Restart influxdb

# Run /usr/local/bin/pinger
- name: Make service unit
  copy:
    src: pinger.service
    dest: /etc/systemd/system
    mode: '0644'
  notify: Reload daemon

- name: Start pinger
  service:
    name: pinger
    state: started