---
- name: Intall Prometheus
  apt:
    name: 
      - prometheus
    force_apt_get: yes

- name: Start Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Configure Prometheus
  template: 
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Make prometheus available
  copy:
    src: prometheus
    dest: /etc/default/prometheus
  notify: Restart Prometheus

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Make sure prometheus is started
  service:
    name: prometheus
    state: started
    enabled: yes