---
- name: Intall Bind9
  apt:
    name: 
      - bind9
    state: present
    force_apt_get: yes

- name: Configure DNS forwarders, ACL, master zone
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart Bind9
    
- name: Configure zone config
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart Bind9

- name: Configure master zone
  template: 
    src: db.premiumfriday.j2
    dest: /var/lib/bind/db.{{ startup_name }}
  notify: Restart Bind9
  when: inventory_hostname in groups['dns_masters']
